# Generated by Django 3.0.7 on 2021-11-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211120_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_day',
        ),
    ]
