# Generated by Django 3.0.7 on 2021-11-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20211120_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Course'),
        ),
    ]
