# Generated by Django 3.2.9 on 2021-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
