# Generated by Django 3.2.9 on 2021-11-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_session_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\DELL\\engage\\account\\static'),
        ),
    ]
