# Generated by Django 3.2.9 on 2021-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_session_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lecture_id',
            field=models.IntegerField(default=0),
        ),
    ]
