# Generated by Django 3.2.9 on 2021-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_attendance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
