# Generated by Django 3.2.9 on 2021-11-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_user_number_of_class_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_end_time',
            new_name='session_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='session_hour',
            field=models.IntegerField(default=1),
        ),
    ]
