# Generated by Django 3.2.9 on 2021-11-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
