# Generated by Django 3.2.9 on 2021-11-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_course_course_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_streak',
        ),
    ]
