# Generated by Django 3.2.9 on 2021-11-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20211127_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
