# Generated by Django 3.2.9 on 2021-11-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_enrollment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='streak',
            new_name='course_streak',
        ),
    ]
