# Generated by Django 3.2.9 on 2021-11-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20211127_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='uploaded',
        ),
    ]
