# Generated by Django 3.2.9 on 2021-11-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_remove_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateField(),
        ),
    ]
