# Generated by Django 3.2.9 on 2021-11-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
