# Generated by Django 3.2.9 on 2021-11-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.TextField(default='Welcome'),
        ),
    ]
